environment:
  GIT_REPOSITORY: https://github.com/wheeler-microfluidics/PMT-transimpedance-amplifier.git
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"

version: 'not set_67b0e900a7e10279f3f6042b76b496c46ce6563b
_appveyor-{build}'

init:
  - "ECHO %PYTHON_VERSION% %MINICONDA%"

install:
  # Exit if no .conda-recipe folder
  - ps: if(!(Test-Path ".conda-recipe")){Add-AppveyorMessage -Message "No Conda Recipe Found" -Category "Error"; throw "Missing .conda-recipe folder"}
  - git clone --depth=1 https://github.com/sci-bots/sci-bots-configs.git
  - powershell -executionpolicy remotesigned -File .\sci-bots-configs\appveyor-install.ps1

# Handle build and tests using conda (defined in .conda-recipe/meta.yaml)
build: false
test_script:
  - echo Build Complete

after_test:
  - powershell -executionpolicy remotesigned -File .\sci-bots-configs\appveyor-after-test.ps1